{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mrbreaknfix",
    "module": "NoReposts",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "NoReposts-1.0.0.jar",
          "url": "NoReposts-1.0.0.jar",
          "size": 19429,
          "sha512": "af546c89d686007e379f190ad4d1fa8b9b97ab82cd230f70d2dd6d115cd17120774312741326f6cf6d1cc0a039461b3a9ee4382c0d2f2cfc1f153538a64499fe",
          "sha256": "5f2b05d87f156d887b60f313b69a2193f9f26989f7d62823b8198b53b17d93e6",
          "sha1": "373dfaa7e147619c3f25795fd5ca0173c8b115ef",
          "md5": "f24d27aa517a2aedde6ba4bd76a99aac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.16.5"
          }
        }
      ],
      "files": [
        {
          "name": "NoReposts-1.0.0.jar",
          "url": "NoReposts-1.0.0.jar",
          "size": 19429,
          "sha512": "af546c89d686007e379f190ad4d1fa8b9b97ab82cd230f70d2dd6d115cd17120774312741326f6cf6d1cc0a039461b3a9ee4382c0d2f2cfc1f153538a64499fe",
          "sha256": "5f2b05d87f156d887b60f313b69a2193f9f26989f7d62823b8198b53b17d93e6",
          "sha1": "373dfaa7e147619c3f25795fd5ca0173c8b115ef",
          "md5": "f24d27aa517a2aedde6ba4bd76a99aac"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "NoReposts-1.0.0-sources.jar",
          "url": "NoReposts-1.0.0-sources.jar",
          "size": 11704,
          "sha512": "6da0d8ea7c4388e0bf79f99a3e18a2012c71a63be0f32cde9a3a7aee4fc624d69026e49547220a3c68f72d19bde348eb40d8fde376937599ddfed55ae0197b0c",
          "sha256": "3cd6d917ff5ed1dfd942261f8dc7217ee5ab3a0617654386918e3dfcc88e536a",
          "sha1": "63bd13c31e4df786da155f4516edfdb72f0b7a66",
          "md5": "44147cc10f0a5411cd9e021b34cf84bf"
        }
      ]
    }
  ]
}
